version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  slack: circleci/slack@3.4.2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:12.9.1-browsers     
    
#     working_directory: ~/repo
    
#     steps:
#       - checkout
    
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-
#       - run: yarn install
    
#       - save_cache:
#           paths:
#             - node_modules
#             - ~/.npm
#             - ~/.cache
#           key: v1-dependencies-{{ checksum "package.json" }}
    
#       - run: yarn build
    
#       - aws-s3/sync:
#           from: build
#           to: "s3://truong-test/"
#           arguments: |
#             --acl public-read \
#             --cache-control "max-age=86400"
#           overwrite: true
jobs:
  app-build:
    parameters:
      # api_endpoint:
      #   type: string
      #   default: http://dev.oppi.live
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    # environment:
    #   CI: false
    #   ENV_FILE_PATH: packages/oppi-frontend/.env

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
  
  app-deploy:
    parameters:
      # environment:
      #   type: string
      #   default: dev
      # frontend_bucket:
      #   type: string
      #   default: oppi-frontend

    executor: aws-cli/default

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - aws-cli/setup:
          profile-name: default

      - run:
          name: Upload to AWS S3
          command: |
            echo "Start build admin"
            aws s3 sync --delete build/ s3://truong-test
            echo "Start create invalidation"
            aws cloudfront create-invalidation --distribution-id EAM4Z2S4XJAAK --paths "/*"
            
            

      # - run:
      #     name: Send API trigger
      #     command: |
      #       echo Send to: ${CIRCLE_PROJECT_API_URL}
      #       curl -X POST ${CIRCLE_PROJECT_API_URL}/build?circle-token=${CIRCLE_CI_TOKEN} -F branch=release/<< parameters.environment >>
      # 
      # echo "Successfully uploaded to s3://S3-truong-test/"
      # curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy latest admin to << parameters.environment >> succeed."}' $SLACK_WEBHOOK_URL
workflows:
  version: 2
  deploy_admin-dev:
    jobs: 
      - app-build:
          # api_endpoint: "https://dev.oppi.live"
          # domain: 'oppi.live'
          filters:
            branches:
              only: /^master/
      - app-deploy:
          # environment: dev
          # frontend_bucket: ${ADMIN_BUCKET_DEV}
          # cf_dist_id: ${ADMIN_DEV_CF_DIST_ID}
          requires:
            - app-build
          filters:
            branches:
              only: /^master/